apiVersion: v1
kind: ServiceAccount
metadata:
  name: webpage-operator
  namespace: local-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webpage-operator
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["example.web.io"]
  resources: ["webpages"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webpage-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webpage-operator
subjects:
- kind: ServiceAccount
  name: webpage-operator
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-operator
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webpage-operator
  template:
    metadata:
      labels:
        app: webpage-operator
    spec:
      serviceAccountName: webpage-operator
      containers:
      - name: manager
        image: webpage-operator:latest
        imagePullPolicy: IfNotPresent
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable:  25% 

---
apiVersion: v1
kind: Service
metadata:
  name: webpage-operator
spec:
  selector:
    app: webpage-operator
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
